name: Build

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set current date as env variable
        run: echo "FILENAME=glove80-${{ github.ref_name }}-$(date +'%Y-%m-%dT%Hh%Mm%Ss')-${{ github.sha }}.uf2" >> $GITHUB_ENV
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: actions/checkout@v3
        with:
          repository: moergo-sc/zmk
          ref: v23.11
          path: src
      - uses: cachix/install-nix-action@v20
        with:
          nix_path: nixpkgs=channel:nixos-22.05
      - uses: cachix/cachix-action@v12
        with:
          name: moergo-glove80-zmk-dev
          skipPush: true
      - name: Build Glove80 combined firmware
        run: nix-build config -o combined
      - name: Copy result out of nix store
        run: cp combined/glove80.uf2 ${{ env.FILENAME }}
      - name: Upload result
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.FILENAME }}
          path: ${{ env.FILENAME }}
